### ISSUE TITLE
[bug / crash] crash when using Immersive Portals (+ iris + sodium)

### ISSUE THREAD

**Issue by TobiPeterG** [mineblock11/FabulousClouds#15]
The game crashes with immersive Portals and Iris and Sodium installed

java.lang.NullPointerException: Unexpected error
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.39)
	at java.util.Objects.requireNonNull(Objects.java:208)
	at net.misterslime.fabulousclouds.client.CloudTexture.lambda$updatePixels$0(CloudTexture.java:40)
	at java.util.Collection.removeIf(Collection.java:576)
	at net.misterslime.fabulousclouds.client.CloudTexture.updatePixels(CloudTexture.java:40)
	at net.misterslime.fabulousclouds.client.NoiseCloudHandler.update(NoiseCloudHandler.java:37)
	at net.minecraft.client.render.WorldRenderer.handler$zmn000$renderClouds(WorldRenderer:6302)
	at net.minecraft.client.render.WorldRenderer.renderClouds(WorldRenderer)
	at net.minecraft.client.render.WorldRenderer.render(WorldRenderer:1434)
	at net.minecraft.client.render.GameRenderer.renderWorld(GameRenderer:1026)
	at net.minecraft.client.render.GameRenderer.redirect$bgo000$redirectRenderingWorld(GameRenderer:4622)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:810)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1112)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:728)
	at net.minecraft.client.main.Main.main(Main:217)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at net.misterslime.fabulousclouds.client.CloudTexture.lambda$updatePixels$0(CloudTexture.java:40)
	at java.base/java.util.Collection.removeIf(Collection.java:576)
	at net.misterslime.fabulousclouds.client.CloudTexture.updatePixels(CloudTexture.java:40)
	at net.misterslime.fabulousclouds.client.NoiseCloudHandler.update(NoiseCloudHandler.java:37)
	at net.minecraft.class_761.handler$zmn000$renderClouds(class_761.java:6302)
	at net.minecraft.class_761.method_3259(class_761.java)
	at net.minecraft.class_761.method_22710(class_761.java:1434)
	at net.minecraft.class_757.method_3188(class_757.java:1026)
	at net.minecraft.class_757.redirect$bgo000$redirectRenderingWorld(class_757.java:4622)

-- Patchouli Book Info --
Details:
	Patchouli open book context: n/a
Stacktrace:
	at net.minecraft.class_128.handler$cjd000$fillPatchouliContext(class_128.java:1521)
	at net.minecraft.class_128.<init>(class_128.java:37)
	at net.minecraft.class_310.method_1514(class_310.java:752)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

-- Affected level --
Details:
	All players: 1 total; [class_746['Tobi_Peter'/139, l='ClientWorld minecraft:overworld', x=365.82, y=67.00, z=1.06]]
	Chunk stats: Client Chunks (ImmPtl) 961
	Level dimension: minecraft:overworld
	Level spawn location: World: (-96,69,-16), Section: (at 0,5,0 in -6,4,-1; chunk contains blocks -96,0,-16 to -81,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 16845 game time, 2080 day time
	Server brand: fabric
	Server type: Integrated singleplayer server

**Comment by misterslime** [comment]
How did you get the crash? Did you go through the portal and it crash? Did lighting the portal crash it?

Edit: nevermind I found the crash.

**Comment by TobiPeterG** [comment]
> 
> 
> How did you get the crash? Did you go through the portal and it crash? Did lighting the portal crash it?
> 
> Edit: nevermind I found the crash.

Ah OK, good.

And yeah, off course I should have told you when the bug occured, forgot to add those information. Sorry. :(

**Comment by misterslime** [comment]
I believe I've fixed the immersive portals crash. Basically being in the nether deletes all the cloud textures for some reason. So I've had to make the clouds use the normal cloud texture for now to get it to work. 0.3.0 is going to bring in a lot of tech I've been working on for Cubic Skies (specifically Cloud Chunks) so the workaround won't be necessary in 0.3.0, as cloud textures won't be a thing anymore.

**Comment by TobiPeterG** [comment]
> I believe I've fixed the immersive portals crash. Basically being in the nether deletes all the cloud textures for some reason. So I've had to make the clouds use the normal cloud texture for now to get it to work. 0.3.0 is going to bring in a lot of tech I've been working on for Cubic Skies (specifically Cloud Chunks) so the workaround won't be necessary in 0.3.0, as cloud textures won't be a thing anymore.

OK, thank you very much for the explanation!

Can you already roughly predict when 0.3 will be a thing? (really just as an orientation, just so I/we know how long I/we have to wait *at least* until the compatibility issues are all fixed :) )

**Comment by misterslime** [comment]
> > I believe I've fixed the immersive portals crash. Basically being in the nether deletes all the cloud textures for some reason. So I've had to make the clouds use the normal cloud texture for now to get it to work. 0.3.0 is going to bring in a lot of tech I've been working on for Cubic Skies (specifically Cloud Chunks) so the workaround won't be necessary in 0.3.0, as cloud textures won't be a thing anymore.
> 
> OK, thank you very much for the explanation!
> 
> Can you already roughly predict when 0.3 will be a thing? (really just as an orientation, just so I/we know how long I/we have to wait _at least_ until the compatibility issues are all fixed :) )

Probably when I'm mostly done cloud generation in Cubic Skies.
